from app.agents.state import AgentState


async def analyze_requirement(state: AgentState) -> AgentState:
    return {**state, "analysis": "MVP mock analysis complete"}


async def generate_code_node(state: AgentState) -> AgentState:
    return {**state, "code": {"html": "<main>Generated by agent node</main>", "css": "", "js": ""}}


async def review_code_node(state: AgentState) -> AgentState:
    return {**state, "review_notes": ["Mock review passed"]}
